apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- app/bia-deploy.yml
- app/bia-service.yml
- ingress.yml

images:
- name: 976808777516.dkr.ecr.us-east-1.amazonaws.com/bia
  newName: 976808777516.dkr.ecr.us-east-1.amazonaws.com/bia
  newTag: 213ff310a59a6c872bfae21c9a4df85638538f99
