apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- app/bia-deploy.yml
- app/bia-service.yml
- ingress.yml

images:
- name: 976808777516.dkr.ecr.us-east-1.amazonaws.com/bia
  newName: 976808777516.dkr.ecr.us-east-1.amazonaws.com/bia
  newTag: 37174460d58239fa22ce7279b0d0d33f23a9e5a6
