name: Limpeza Total de Runs
on:
  workflow_dispatch:

jobs:
  delete-runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Deletar runs concluidas via Script CLI
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
        run: |
          # O --status completed garante que ele não tente apagar a si mesmo
          gh run list --status completed --limit 1000 --json databaseId --jq '.[].databaseId' | xargs -I{} gh run delete {} || true