name: Limpeza Total de Runs
on:
  workflow_dispatch:

jobs:
  delete-runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Deletar todas as runs via Script CLI
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Lista todas as runs, pega o ID e deleta uma por uma
          gh run list --limit 1000 --json databaseId --jq '.[].databaseId' | xargs -I{} gh run delete {}