name: Limpeza Total de Runs
on:
  workflow_dispatch:

jobs:
  delete-runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write # Permissão crucial para deletar
    steps:
      - name: Delete workflow runs
        uses: lowply/delete-workflow-runs-action@v1.0.1
        with:
          repository: ${{ github.repository }}
          github_token: ${{ github.token }}
          delete_run_by_days_old: 0